### ISSUE TITLE
Check in install_via_apt.pl, if the requested versions got installed

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#197]
Background:
- When customizing flavors we might need to reinstall packages in a different version
- Some options can prevent this, so we need at least a warning, but more often we need to fail

Acceptance Criteria:
- Implement comparison between installed and requested packages and versions
- Add option to toggle between warning and fail
- Print comparison when they don't match

**Comment by redcatbear** [comment]
Closing as duplicate of #196. @tkilias, c&p error?
