### ISSUE TITLE
Add release of M1 of bucketfs-utils-python and data-science-utils-python to standard and python-datascience flavor

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#257]
## Background

- We provide these two python libraries for our customers and they expect that they can use them in our UDFs without further installation.

https://github.com/exasol/bucketfs-utils-python/milestone/1
https://github.com/exasol/data-science-utils-python/milestone/1

## Acceptance Criteria

- Add the packages to the package lists of flavor-base-deps. Note: currently you need to install them via git, we need to change this as soon they get released to pypi
- We need tests for the two libraries, because there can be python package version issues with the python package installed via apt

**Comment by tomuben** [comment]
@tkilias am I right assuming that tests should be stored [here](https://github.com/exasol/script-languages/tree/5148ec455ca4c8322c3adcccbeee8bcd02f05e07/tests/lang/python3)?

**Comment by tomuben** [comment]
Create a new folder for tests [here](https://github.com/exasol/script-languages/tree/5148ec455ca4c8322c3adcccbeee8bcd02f05e07/tests/test)

**Comment by tkilias** [comment]
data-science-utils-python is depricated and bucketfs-utils-python got included into standard flavor for Exasol 8.0 with https://github.com/exasol/script-languages-release/pull/464. The Data Science flavor don't exist anymore and the old standard flavor stay as they are, so we can close this issue.
