### ISSUE TITLE
Ubuntu package software-properties-common depends on python3 and adds it to the non python flavors

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#260]
## Background

- Currently, we install in all flavors software-properties-common it gives us apt-add-repository https://askubuntu.com/questions/1000118/what-is-software-properties-common
- However, it depends on python3 and as such includes python3 into non-python flavors and makes them unnecessary large
- We need to think about, if we want to remove it and replace the functionality, or if we keep it and maybe use python3 for management scripts during build.
- If we want to remove it, we need to check which dependencies we need. 
- If we want to keep python3 for scripting, then we need to check its size

**Comment by tomuben** [comment]
Try to remove software-properties-common after installing additional repositories (run all in one docker run step) and run apt purge.
(create a helper script).
