### ISSUE TITLE
Java EMITS UDF Scripts cannot emit null

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#31]
```
CREATE OR REPLACE JAVA SCALAR SCRIPT TEST.java_test() EMITS(i INT) AS 
class JAVA_TEST {
 static void run(ExaMetadata exa, ExaIterator ctx) throws Exception {
  ctx.emit(null);
 }
}
/

CREATE OR REPLACE PYTHON SCALAR SCRIPT TEST.python_test() EMITS(i INT) AS
def run(ctx):
 ctx.emit(None)
/

select test.java_test();   -- NullPointerException
select test.python_test(); -- works
```

Backtrace:

> 07.01 10:03:21.839 writeException: 22002 VM error: 
> java.lang.NullPointerException 
> Stack trace:   
> com.exasol.ExaIteratorImpl.emit(ExaIteratorImpl.java:73)   
> com.exasol.JAVA_TEST.run(JAVA_TEST.java:4) 
> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)   
> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   
> java.base/java.lang.reflect.Method.invoke(Method.java:566) 
> com.exasol.ExaWrapper.run(ExaWrapper.java:186) (Session: 1655054869230996830)

**Comment by stmandl** [comment]
Emitting the empty string would produce the SQL NULL value, right?

**Comment by tkilias** [comment]
I need look into the code here, what we are doing there. I think, the problem is that we don't catch the case. However, I think the empty string would give you a cast exception.

**Comment by tkilias** [comment]
Ok, with ctx.emit(null) the parameter values in the [emit method](https://github.com/exasol/script-languages/blob/b5b59de320ee8f4ef8f90d292e2eaa83141a8faa/exaudfclient/base/javacontainer/ExaIteratorImpl.java#L69) is not an array. It is then null and then values.length in https://github.com/exasol/script-languages/blob/b5b59de320ee8f4ef8f90d292e2eaa83141a8faa/exaudfclient/base/javacontainer/ExaIteratorImpl.java#L73 throws a NullPointerException. So, we need to check if the values parameter is null.

**Comment by tkilias** [comment]
Reopening, because performance degradation of 5%

```
diff --git a/exaudfclient/base/javacontainer/ExaIteratorImpl.java b/exaudfclient/base/javacontainer/ExaIteratorImpl.java
index bdf2ec3..20f791c 100644
--- a/exaudfclient/base/javacontainer/ExaIteratorImpl.java
+++ b/exaudfclient/base/javacontainer/ExaIteratorImpl.java
@@ -70,16 +70,7 @@ class ExaIteratorImpl implements ExaIterator {
         if (insideRun && singleOutput)
             throw new ExaIterationException("emit() function is not allowed in scalar context");
 
-        if(values == null){
-          if(exaMetadata.getOutputColumnCount()==1){
-            resultHandler.setNull(0);
-          }else{
-            String errorText = "emit() takes exactly " + exaMetadata.getOutputColumnCount();
-            errorText += (exaMetadata.getOutputColumnCount() > 1) ? " arguments" : " argument";
-            errorText += " (" + 1 + " given)";
-            throw new ExaIterationException(errorText);
-          }
-        }else{
+        if(values != null){
             if (values.length != exaMetadata.getOutputColumnCount()) {
                 String errorText = "emit() takes exactly " + exaMetadata.getOutputColumnCount();
                 errorText += (exaMetadata.getOutputColumnCount() > 1) ? " arguments" : " argument";
@@ -202,6 +193,15 @@ class ExaIteratorImpl implements ExaIterator {
                     throw new ExaIterationException(exMsg);
                 }
             }
+        }else{
+            if(exaMetadata.getOutputColumnCount()==1){
+              resultHandler.setNull(0);
+            }else{
+              String errorText = "emit() takes exactly " + exaMetadata.getOutputColumnCount();
+              errorText += (exaMetadata.getOutputColumnCount() > 1) ? " arguments" : " argument";
+              errorText += " (" + 1 + " given)";
+              throw new ExaIterationException(errorText);
+            }
         }
 
         boolean next = resultHandler.next();

```
