### ISSUE TITLE
Wrong license URL in pom of exasol-script-api

### ISSUE THREAD

**Issue by jakobbraun** [exasol/script-languages-release#310]
In the pom of `exasol-script-api` there is a non-reachable URL for the license. Since it's a MIT license we can probably just use https://opensource.org/licenses/MIT

**Comment by tkilias** [comment]
Depends on https://github.com/exasol/script-languages-release/issues/111

**Comment by tkilias** [comment]
Solved by extracting the API into it own repo with https://github.com/exasol/udf-api-java/issues/1.
