### ISSUE TITLE
Prepare standard container for the next Exasol version

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#382]
# Background

- for the next Exasol release some major changes are planned for the script-language containers

# Acceptance Criteria

- Python 3.8 -> Ubuntu 20.04 -> Complete new versions for apt packages
- Activate new Pip dependency resolver -> complete new set of python package versions -> no python packages over apt
- Remove Python2

# Depends on

see also

- [x] https://github.com/exasol/script-languages-release/issues/332
- [x] https://github.com/exasol/script-languages-release/issues/331
- [x] https://github.com/exasol/script-languages-release/issues/383
- [x] https://github.com/exasol/script-languages-release/issues/412
- [x] https://github.com/exasol/script-languages-release/issues/118
- [x] https://github.com/exasol/script-languages-release/issues/333

**Comment by tomuben** [comment]
List of candiates to be removed:

- python3-pygments
