### ISSUE TITLE
Add security scan for flavors

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#383]
Add security scan to the flavors. See https://github.com/exasol/script-languages-container-tool/issues/81

Steps:
- Create build step security scan
- Run security scan in CI

Flavors:

- [ ] standard flavor 7.0
- [ ] standard flavor 7.1
- [ ] standard flavor new
- [x] python 3.6 minimal 
- [x] python 3.7 minimal
- [x] python 3.8 minimal
- [ ] r 4.1 minimal
- [ ] r 3.5 data science
- [ ] python 3.6 data science

**Comment by tomuben** [comment]
For scope of this ticket we decided to implement the following tools:

- https://github.com/sonatype-nexus-community/oysteR
- https://aquasecurity.github.io/trivy/v0.21.1/vulnerability/scanning/rootfs/
