### ISSUE TITLE
Avoid creating wheel cache in install_via_pip

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#395]
# Background

It seems, that we create regardless of the --no-cache-dir option create a package cache for pip in
https://github.com/exasol/script-languages/blob/a81ebd63c2556c178a1b0f87ea219bcb87acc41e/ext/scripts/install_scripts/install_via_pip.pl#L56

**Comment by tomuben** [comment]
More info's:
https://pip.pypa.io/en/stable/cli/pip_cache/#pip-cache

**Comment by tomuben** [comment]
## Findings

1. ```pip install ``` with __--no-cache-dir__ works, no cache is beeing created
2. pip installation itself creates already a cache dir with 2 packages: http and selfcheck
3. ```pip list``` also creates a pip cache

## Solution

1. Remove cache directory after pip installation  (No option was found to suppress creation of cache directory during pip installation)
2. Apply __no-cache-dir__ for ```pip install```
