### ISSUE TITLE
Remove more unnecessary files from Ubuntu

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#412]
## Background

We want the script-language container to be as lean as possible.

Maybe we can take some ideas from:
https://wiki.ubuntu.com/ReducingDiskFootprint#Drop_unnecessary_files
https://github.com/palletops/docker-ubuntu-nodoc

**Comment by tkilias** [comment]
It seems these two links don't offer new optimizations. Out no_doc file is identical to theirs.
