### ISSUE TITLE
Add a security-scan script to the latest standard container

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#428]
## Background

With #383 we already run security scans in CI build for **new** containers.
However, it would be important to have a simple tool which enables us to run easily security scans on script language containers, already shipped with the database. For example, consider the log4j vulnerability nightmare, it would be good if we can rapidly check if any of the delivered script language container is affected.

## Acceptance Criteria

Implement a simple script which is included in the latest standard script language container, which installs trivy and runs it. This script then can be triggered then by an UDF.

**Comment by tkilias** [comment]
We changed this a bit and installed trivy and oysteR directly into the container and the security scanner bash script is already available, because we copy the whole script directory
