### ISSUE TITLE
Remove legacy install scripts

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#451]
## Background 

[Here](https://github.com/exasol/script-languages/pull/251/files#r777978713)  we discovered that some build steps still use the bash install scripts, but we should switch to the perl scripts.

## Acceptance Criteria

Change all build steps to use the perl scripts for any package installation.
Remove parse_single_line_package_list_with_comments.sh and any related script.

**Comment by tkilias** [comment]
r-3.5 -datascience flavor doesn't exists anymore and it was the last user of install_packages_batch.sh which is the only user of parse_single_line_package_list_with_comments.sh. We can remove these two files.
