### ISSUE TITLE
Add GitHub Action on Mac to test the exaslct starter scripts in dry_run mode

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#485]
# Background:

- we can't test the whole system on Mac on Github Actions, because it doesn't support Docker, but we can test the starter_scripts in a dry_run mode in which we don't execute the docker command
- Needs: https://github.com/exasol/script-languages-container-tool/issues/107

**Comment by tomuben** [comment]
We decided to shelve this issue because it's probably not necessary to run the test again in script-language-release.
