### ISSUE TITLE
Move AbstractPerformanceTest tests to exasol-python-test-framework 

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#501]
## Background

We extracted the UDF Test FW to exasol-python-test-framework.
The AbstractPerformanceTest is currently used by tests under performance/* and performance/very_large. It makes sense to move this abstract class to the FW and include it in both directories from the exasol-python-test-framework package.

## Acceptance Criteria

- Move AbstractPerformanceTest  to exasol-python-test-framework and use it in  performance/* and performance/very_large from there
- Replace generate_linear and generate_exponential with more generic version in exasol-python-test-framework
  - https://github.com/exasol/exasol-python-test-framework/blob/c54f373924085f0aa423caeb9ee7883ca34377c7/exasol_python_test_framework/udf/__init__.py#L359
  - Unify comparison with built-in container  
    -  AbstractPerformanceTest
    - https://github.com/exasol/exasol-python-test-framework/blob/c54f373924085f0aa423caeb9ee7883ca34377c7/exasol_python_test_framework/udf/__init__.py#L383

**Comment by tkilias** [comment]
Obsolete, exatest will be replaced in future
