### ISSUE TITLE
Push test container to Dockerhub

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#573]
## Background

We currently push the Test-Container of the Integration-test-docker-environment to Dockerhub, check [here](https://github.com/exasol/integration-test-docker-environment/blob/68c4f4c9eda0a6f02ec474dd2f129d45214b38a7/.github/workflows/publish_docker_runner.yml#L29).

We should do the same for the custom Test-Container of the script-languages, as this will accelerate the CI runs (container can be pulled and don't need to be built everytime during the CI).

## Acceptance Criteria

Push test-container in script-languages repository every time a PR is integrated to master branch.

**Comment by tkilias** [comment]
This is not only about CI it is also for users which run the tests on customized flavor
