### ISSUE TITLE
Remove virtualschema-jdbc-adapter.jar

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#588]
Remove virtualschema-jdbc-adapter.jar from script-languages-* and integration-test-docker-environment

https://github.com/exasol/script-languages/blob/67aa452ab4e05f6ddb185565a154bef742031378/tests/Dockerfile#L26

**Comment by tomuben** [comment]
Need to fix https://github.com/exasol/integration-test-docker-environment/issues/213 before this one.
