### ISSUE TITLE
Unable to load native library in Standard Flavor with Virtual Schemas and Exasol 6.2

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#6]
For unknown reasons the Virtual Schemas don't work with the current master of the script-languages. The standard container delivered with Exasol 6.2 seems not to be affected. The error happens while the initialization of JVM, so only Java seems to be affected. The tests for the Java-UDFs were all green during build and worked. 
My current guess is that something goes wrong during loading of JNI Libraries in some JDBC Drivers. An interesting fact is, that the JVM crashed during initialization. At this point, no user specific code should run. So, it might be some static loads in the jar files or something like that. It also might be correlated to the update of the Virtual Schemas to Java 9.

Here is the Output of the FlavorTest Build of the Standard Flavor:

> 27.1.0.10:33408> Changing to script directory  /exaudf
> 27.1.0.10:33408> DBG: exaudfclient.cc(98) in main Load libexaudflib
> 27.1.0.10:33408> DBG: exaudfclient.cc(99) in main VAR: libexaudflibPath = [/exaudf/libexaudflib_complete.so]
> 27.1.0.10:33408> zmqcontainerclient argv[0] = ./exaudfclient
> 27.1.0.10:33408> zmqcontainerclient argv[1] = ipc:///tmp/zmqvmcontainer_conn_7830610158718577077
> 27.1.0.10:33408> zmqcontainerclient argv[2] = lang=java
> 27.1.0.10:33408> ### SWIGVM starting ./exaudfclient with name 'ipc:///tmp/zmqvmcontainer_conn_7830610158718577077 (1,5): 'ipc:///tmp/zmqvmcontainer_conn_7830610158718577077'
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(1554) in exaudfclient_main Reinit
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(96) in external_process_check VAR: &(socket_name_file) = [0x7f29a3aa60c0]
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:33408> ### SWIGVM connected with id 6cabea7374fc69b5
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:33408> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(111) CALL BEGIN: setClasspath()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(111) CALL END: setClasspath()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(112) CALL BEGIN: getScriptClassName()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(112) CALL END: getScriptClassName()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(113) CALL BEGIN: importScripts()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(113) CALL END: importScripts()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(114) CALL BEGIN: addPackageToScript()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(114) CALL END: addPackageToScript()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(115) CALL BEGIN: addExternalJarPaths()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(115) CALL END: addExternalJarPaths()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(116) CALL BEGIN: getExternalJvmOptions()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(116) CALL END: getExternalJvmOptions()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(117) CALL BEGIN: setJvmOptions()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(117) CALL END: setJvmOptions()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(118) CALL BEGIN: createJvm()
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Dexasol.scriptclass=com.exasol.adapter.RequestDispatcher]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xms128m]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xmx1024m]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xss512k]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:ErrorFile=/tmp/hs_err_pid%p.log]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Djava.class.path=/tmp:/exaudf/javacontainer/libexaudf.jar:/buckets/bfsdefault/postgres/postgresql-42.2.6.jar:/buckets/bfsdefault/postgres/virtualschema-jdbc-adapter-dist-2.0.1.jar]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:+UseSerialGC]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(255) in createJvm VAR: m_env = [0]
> 27.1.0.10:33408> DBG: javacontainer/javacontainer.cc(257) CALL BEGIN: int rc = JNI_CreateJavaVM(&m_jvm, (void**)&m_env, &vm_args)
> 27.1.0.10:33408> Error occurred during initialization of VM
> 27.1.0.10:33408> Unable to load native library: �?��)
>

**Comment by AnastasiiaSergienko** [comment]
Virtual Schema 1.19.1 and Postgres

> >>> bind the output server to 27.1.0.10:3000
> 27.1.0.10:56912> Changing to script directory  /exaudf
> 27.1.0.10:56912> DBG: exaudfclient.cc(98) in main Load libexaudflib
> 27.1.0.10:56912> DBG: exaudfclient.cc(99) in main VAR: libexaudflibPath = [/exaudf/libexaudflib_complete.so]
> 27.1.0.10:56912> zmqcontainerclient argv[0] = ./exaudfclient
> 27.1.0.10:56912> zmqcontainerclient argv[1] = ipc:///tmp/zmqvmcontainer_conn_1565913098349702276
> 27.1.0.10:56912> zmqcontainerclient argv[2] = lang=java
> 27.1.0.10:56912> ### SWIGVM starting ./exaudfclient with name 'ipc:///tmp/zmqvmcontainer_conn_1565913098349702276 (1,5): 'ipc:///tmp/zmqvmcontainer_conn_1565913098349702276'
> 27.1.0.10:56912> DBG: exaudflib/exaudflib.cc(1554) in exaudfclient_mainDBG:  Reinit
> 27.1.0.10:56912> exaudflib/exaudflib.cc(96) in external_process_check VAR: &(socket_name_file) = [0x7f470631c0c0]
> 27.1.0.10:56912> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:56912> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:56912> ### SWIGVM connected with id 15bb3daa9843ec84
> 27.1.0.10:56912> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:56912> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(111) CALL BEGIN: setClasspath()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(111) CALL END: setClasspath()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(112) CALL BEGIN: getScriptClassName()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(112) CALL END: getScriptClassName()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(113) CALL BEGIN: importScripts()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(113) CALL END: importScripts()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(114) CALL BEGIN: addPackageToScript()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(114) CALL END: addPackageToScript()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(115) CALL BEGIN: addExternalJarPaths()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(115) CALL END: addExternalJarPaths()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(116) CALL BEGIN: getExternalJvmOptions()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(116) CALL END: getExternalJvmOptions()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(117) CALL BEGIN: setJvmOptions()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(117) CALL END: setJvmOptions()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(118) CALL BEGIN: createJvm()
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Dexasol.scriptclass=com.exasol.adapter.RequestDispatcher]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xms128m]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xmx1024m]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xss512k]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:ErrorFile=/tmp/hs_err_pid%p.log]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Djava.class.path=/tmp:/exaudf/javacontainer/libexaudf.jar:/buckets/bfsdefault/postgres/postgresql-42.2.6.jar:/buckets/bfsdefault/postgres/virtualschema-jdbc-adapter-dist-1.19.1.jar]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:+UseSerialGC]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(255) in createJvm VAR: m_env = [0]
> 27.1.0.10:56912> DBG: javacontainer/javacontainer.cc(257) CALL BEGIN: int rc = JNI_CreateJavaVM(&m_jvm, (void**)&m_env, &vm_args)
> 27.1.0.10:56912> Error occurred during initialization of VM
> 27.1.0.10:56912> Unable to load native library: ocs_runn�
>

**Comment by AnastasiiaSergienko** [comment]
Virtual Schema 2.0.0 and Postgres. Exasol 6.2.1

> >>> bind the output server to 27.1.0.10:3000
> 27.1.0.10:51320> Changing to script directory  /exaudf
> 27.1.0.10:51320> DBG: exaudfclient.cc(98) in main Load libexaudflib
> 27.1.0.10:51320> DBG: exaudfclient.cc(99) in main VAR: libexaudflibPath = [/exaudf/libexaudflib_complete.so]
> 27.1.0.10:51320> zmqcontainerclient argv[0] = ./exaudfclient
> 27.1.0.10:51320> zmqcontainerclient argv[1] = ipc:///tmp/zmqvmcontainer_conn_16868446663686457525
> 27.1.0.10:51320> zmqcontainerclient argv[2] = lang=java
> 27.1.0.10:51320> ### SWIGVM starting ./exaudfclient with name 'ipc:///tmp/zmqvmcontainer_conn_16868446663686457525 (1,5): 'ipc:///tmp/zmqvmcontainer_conn_16868446663686457525'
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(1554) in exaudfclient_main Reinit
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(96) in external_process_check VAR: &(socket_name_file) = [0x7f5508d2f0c0]
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:51320> ### SWIGVM connected with id ea18c2de25a788b5
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:51320> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(111) CALL BEGIN: setClasspath()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(111) CALL END: setClasspath()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(112) CALL BEGIN: getScriptClassName()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(112) CALL END: getScriptClassName()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(113) CALL BEGIN: importScripts()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(113) CALL END: importScripts()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(114) CALL BEGIN: addPackageToScript()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(114) CALL END: addPackageToScript()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(115) CALL BEGIN: addExternalJarPaths()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(115) CALL END: addExternalJarPaths()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(116) CALL BEGIN: getExternalJvmOptions()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(116) CALL END: getExternalJvmOptions()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(117) CALL BEGIN: setJvmOptions()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(117) CALL END: setJvmOptions()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(118) CALL BEGIN: createJvm()
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Dexasol.scriptclass=com.exasol.adapter.RequestDispatcher]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xms128m]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xmx1024m]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xss512k]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:ErrorFile=/tmp/hs_err_pid%p.log]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Djava.class.path=/tmp:/exaudf/javacontainer/libexaudf.jar:/buckets/bfsdefault/postgres/postgresql-42.2.6.jar:/buckets/bfsdefault/virtualschemas/virtualschema-jdbc-adapter-dist-2.0.0.jar]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:+UseSerialGC]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(255) in createJvm VAR: m_env = [0]
> 27.1.0.10:51320> DBG: javacontainer/javacontainer.cc(257) CALL BEGIN: int rc = JNI_CreateJavaVM(&m_jvm, (void**)&m_env, &vm_args)
> 27.1.0.10:51320> Error occurred during initialization of VM
> 27.1.0.10:51320> Unable to load native library:  0 0 0 0�

**Comment by redcatbear** [comment]
Same error on my machine:

> >>> bind the output server to 27.1.0.10:3000
> 27.1.0.10:44844> Changing to script directory  /exaudf
> 27.1.0.10:44844> DBG: exaudfclient.cc(98) in main Load libexaudflib
> 27.1.0.10:44844> DBG: exaudfclient.cc(99) in main VAR: libexaudflibPath = [/exaudf/libexaudflib_complete.so]
> 27.1.0.10:44844> zmqcontainerclient argv[0] = ./exaudfclient
> 27.1.0.10:44844> zmqcontainerclient argv[1] = ipc:///tmp/zmqvmcontainer_conn_2903532436482083333
> 27.1.0.10:44844> zmqcontainerclient argv[2] = lang=java
> 27.1.0.10:44844> ### SWIGVM starting ./exaudfclient with name 'ipc:///tmp/zmqvmcontainer_conn_2903532436482083333 (1,5): 'ipc:///tmp/zmqvmcontainer_conn_2903532436482083333'
> 27.1.0.10:44844> DBG: exaudflib/exaudflib.cc(1554) in exaudfclient_main Reinit
> 27.1.0.10:44844> DBG: exaudflib/exaudflib.cc(96) in external_process_check VAR: &(socket_name_file) = [DBG: exaudflib/exaudflib.cc(0x97) BEGIN FUNC: socket_send
> 27.1.0.10:44844> DBG: exaudflib/exaudflib.cc(0xc0) BEGIN FUNC: socket_recv
> 27.1.0.10:44844> 0x7fabd88800c0]
> 27.1.0.10:44844> ### SWIGVM connected with id 284b6b5e0e56ca05
> 27.1.0.10:44844> DBG: exaudflib/exaudflib.cc(151) BEGIN FUNC: socket_send
> 27.1.0.10:44844> DBG: exaudflib/exaudflib.cc(192) BEGIN FUNC: socket_recv
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(111) CALL BEGIN: setClasspath()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(111) CALL END: setClasspath()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(112) CALL BEGIN: getScriptClassName()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(112) CALL END: getScriptClassName()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(113) CALL BEGIN: importScripts()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(113) CALL END: importScripts()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(114) CALL BEGIN: addPackageToScript()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(114) CALL END: addPackageToScript()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(115) CALL BEGIN: addExternalJarPaths()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(115) CALL END: addExternalJarPaths()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(116) CALL BEGIN: getExternalJvmOptions()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(116) CALL END: getExternalJvmOptions()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(117) CALL BEGIN: setJvmOptions()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(117) CALL END: setJvmOptions()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(118) CALL BEGIN: createJvm()
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Dexasol.scriptclass=com.exasol.adapter.RequestDispatcher]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xms128m]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xmx1024m]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Xss512k]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:ErrorFile=/tmp/hs_err_pid%p.log]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-Djava.class.path=/tmp:/exaudf/javacontainer/libexaudf.jar:/buckets/bfsdefault/jars/postgresql-42.2.6.jar:/buckets/bfsdefault/jars/virtualschema-jdbc-adapter-dist-2.0.0.jar]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(245) in createJvm VAR: options[i].optionString = [-XX:+UseSerialGC]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(255) in createJvm VAR: m_env = [0]
> 27.1.0.10:44844> DBG: javacontainer/javacontainer.cc(257) CALL BEGIN: int rc = JNI_CreateJavaVM(&m_jvm, (void**)&m_env, &vm_args)
> 27.1.0.10:44844> Error occurred during initialization of VM
> 27.1.0.10:44844> Unable to load native library:  0 0 0 0

**Comment by tkilias** [comment]
We were able to locate the commit which introduces the bug.
https://github.com/exasol/script-languages/commit/dd54f66fdaaa4f10dcb85cd2ab65bbf74aafd07d
We are going to check which causes the bug.
