### ISSUE TITLE
Investigate to run exalsct in docker container to better support MacOSX and Windows

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#66]
Situation:
- exalsct needs a linux system to run properly
- a Linux VM is quite heavy to install for the build
- Maybe it is possible to start exalsct in a docker container with a linux system and mount the docker socket into this container. Then exaslct can spawn new container to build the script-language container

Todo:
- test docker-socket mounting on MacOSX and Windows
- prepare a container to run exaslct in
- change start up script of exaslct to run exaslct in the container and mount the socket

**Comment by tkilias** [comment]
Mount host directory into containers on non Linux systems

Docker for MacOSX 
https://docs.docker.com/docker-for-mac/osxfs/

Docker for Windows
https://docs.docker.com/docker-for-windows/#/shared-drives
Question: How to mount docker socket?

**Comment by andyscheel** [comment]
Docker socket should be mountable on all OS's with architecture depending mounts

Mac/Linux
> -v "/var/run/docker.sock:/var/run/docker.sock"

Windows
> to be tested:
> -v \\.\pipe\docker_engine:\\.\pipe\docker_engine

**Comment by tkilias** [comment]
This ticket will be closed by #249 , because after the extraction of exalsct to https://github.com/exasol/script-languages-container-tool/, it usually runs in a docker container and only requires a wrapper script for the specific operating system. At the moment, the wrapper script doesn't work for MacOS, but it isn't too difficult to adapt that. And for windows we have to develop one. However, these are new issues for https://github.com/exasol/script-languages-container-tool/,
