### ISSUE TITLE
way to upgrade pip-version used for installing python3-packages?

### ISSUE THREAD

**Issue by djamadeus** [exasol/script-languages-release#744]
I added the pip install upgrade pip commnd to the Docker-file of the 7.1 flavor trying to be able use the most actual versions of the packages, but it still uses an older pip-version, recognizing only packages-versions from a year ago...
is there any way to get the actual ones/upgrade the included pip?

**Comment by redcatbear** [comment]
@tomuben, this is your area of expertise. Can you answer this question, please.

**Comment by djamadeus** [comment]
@tomuben great to know, thanks!

**Comment by djamadeus** [comment]
Could I also try to install python 3.10 on this, or is there any specific compatibility reason why you still stick to 3.8?

**Comment by redcatbear** [comment]
@djamadeus, as @tomuben mentioned, the LC is based on an Ubuntu LTS Linux. We usually only install versions that come pre-shipped with a each version. Manually upgrading is theoretically possible as long as you are prepared to handle any extra dependencies by hand to.

I am not a Python expert, but I think as far as I know Python's dependencies are moderate.

Long story short: if Exasol switches to all new versions, that usually comes with a more uptodate Ubuntu LTS Linux.

**Comment by djamadeus** [comment]
understood. I'll give it a try anyways, and if it works share it so you can add it to the repo if you like

**Comment by tomuben** [comment]
@djamadeus , updating the Python version in an SLC is a bit more complicated. You need to build the UDF-client with the correct Python environment (see [here](https://github.com/exasol/script-languages/blob/e27643b753c4db5f0d3306dcb1601191c4b17641/flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/Dockerfile#L19) ). 
I would suggest to use the Python3.7-minimal flavor as base; (or alternatively the Python3.8-minimal which is already based on Ubuntu 20.04, but then you need to add the deadsnakes ppa): This builds a Python specific Script-Languages-Container where you don't need to worry about other dependencies (R, Java). On this flavor you can then add your desired Python packages.

As Sebastian commented, for the standard-container we try to avoid adding more dependencies than necessary (for example the deadsnakes ppa), as we have to maintain them for a long time.

**Comment by redcatbear** [comment]
I am closing the ticket here, because it has no effect on the currently provided standard language containers.
