### ISSUE TITLE
R UDFs with empty run function hangs

### ISSUE THREAD

**Issue by stmandl** [exasol/script-languages-release#754]
This UDF does not terminate and eventually runs out of memory:
```R
create schema test;

create or replace R scalar script test.dummy()
returns int AS 
run <- function(ctx) {
}
/


select test.dummy();
```

**Comment by tkilias** [comment]
The problem occurs, because an empty function returns NULL. I tried to return NULL directly and got the same error. We probably expect a vector as return value, and everything in R is a vector except NULL. Also, a vector of NULL is NULL
