### ISSUE TITLE
Documentation, section prerequisites

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/script-languages-release#78]
There should be a remark in the prerequisites section, that you need to execute the statements as root

**Comment by tkilias** [comment]
@exaValerieWiedemann it is not specifically root what you need, it is in general access to the docker socket, usually under `/var/run/docker.sock` in Linux and Mac. This can be achieved, either by being root, using sudo or if your user was added to the docker group. I will think of a phrase which we can add to the README. Maybe, I find a good explanation for this in the docker documentation.

**Comment by tkilias** [comment]
Maybe we can link to this explanation

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

**Comment by tomuben** [comment]
Added a link to https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user. Which contains more information about how to run docker not as root.
