### ISSUE TITLE
E: Version '11.0.20+8-1ubuntu1~20.04' for 'openjdk-11-jdk-headless' was not found

### ISSUE THREAD

**Issue by djamadeus** [exasol/script-languages-release#839]
The current msater fails building container with the error msg
`E: Version '11.0.20+8-1ubuntu1~20.04' for 'openjdk-11-jdk-headless' was not found`

Failed to run apt-get install -V -y --no-install-recommends 'ca-certificates=20230311ubuntu0.20.04.1' 'python3.8-dev=3.8.10-0ubuntu1~20.04.8' 'python3-distutils=3.8.10-0ubuntu1~20.04' 'curl=7.68.0-1ubuntu2.19' 'openjdk-11-jdk-headless=11.0.20+8-1ubuntu1~20.04' at /scripts/install_scripts/package_mgmt_utils.pm line 175.

**Comment by tkilias** [comment]
Hi @djamadeus,

Thank you for letting us know. I will update the dependency and push afterthat a new version to the master.

**Comment by tkilias** [comment]
@djamadeus I merged the updates to the master. If no other packages got outdated over the night, it should work again.
