### ISSUE TITLE
Add support for Java UDFs on the module path

### ISSUE THREAD

**Issue by kaklakariada** [exasol/script-languages-release#881]
Currently it is not possible to add JARs to the module path.

Executing the following UDF with a modularized JAR fails with error message `F-UDF-CL-SL-JAVA-1042: FindClass for com.exasol.ExaUndefinedSingleCallException failed`.
```sql
CREATE JAVA SCALAR SCRIPT JAVA_MODULE_TEST() RETURNS INT AS
%scriptclass com.exasol.slc.testudf.Main;
%jvmoption --module-path={java_udf_jar_bucketfs_path}:/buckets/default/udf-api-java-1.0.5.jar;
%jvmoption --add-exports=java.base/sun.security.x509=ALL-UNNAMED;
%jvmoption --add-modules=ALL-MODULE-PATH;
```
Adding `/exaudf/javacontainer/libexaudf.jar` additionally to the module path results in this error:
```
java.lang.module.ResolutionException: Module udf.api.java contains package com.exasol, module libexaudf exports package com.exasol to udf.api.java
```

To solve this, we need to extract the UDF API from `libexaudf.jar` and let `libexaudf.jar` depend on `udf-api-java-1.0.5.jar`.

**Comment by redcatbear** [comment]
Since no customer required that, we will close this ticket for now. We can reopen it once we get an explicit request.
