### ISSUE TITLE
Add actual package lists to images at end of image building

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#92]
Situation: 

Currently, we only add the package lists for the install scripts to the images. These only contain the expected packages, but not the actual installed packages. Usually, the package lists for install scripts don't contain all packages, only those which must be in the container. However, package systems will install further package to resolve dependencies. With the list of actuall installed packages, we can better trace back what is in the container and can use diagnostic UDF to show what is available in an installed container. Furthermore, we can check if all packages got installed which is important for R because it can silently omit packages and it can be difficult to recognize such an error in the build logs.

Tasks:

- [x] If not available create scripts which extract the actual installed packages and format them in the same format as the package lists for the install script, such that comparison is easy 
- [ ] At the release step of the flavor run the scripts to extract the actual installed packages
- [ ] Compare the actual installed packages with requested ones and fail the build if requested once are not available. This requires that all flavors and steps use the new install script and their package list format.

**Comment by tomuben** [comment]
Task 1&2 are already fixed. For task 3 we created a separate ticket: #557
