### ISSUE TITLE
Add CTPG script options parser

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#967]
## Background

Part of https://github.com/exasol/script-languages-release/issues/652
This task is part of our effort to implement a more robust script options parser for the UDF client.

## Acceptance Criteria
1. Add Script Options parser based on [CTPG library](https://github.com/peter-winter/ctpg).
2. The goal is to have a parser which can parse generic script options and return the found script option keys + values.
3. Unit tests which validate correct behavior of the parser when applying to different UDF's with script options.

## What is not scope of the task
1.  No modification of the original script code needed (as is done in the legacy parser).
2. No integration of the new parser in Java VM of the udf client

**Comment by redcatbear** [comment]
Review: +3h

**Comment by Nicoretti** [comment]
3h review time from @redcatbear
