### ISSUE TITLE
Add environment variable for new ScriptOptionsLine parser in UDF client

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#986]
## Background

We have implemented the new Script Options parser in the UDF client. A new option in the UDF clients needs to be implemented, in order to expose the new parser to clients. Per default, the legacy parser should be used, because of compatiblity issues (the new parser supports escape sequences for \t, \n, \;).

The database does not forward single arguments of the query to the UDF client. As workaround we can use an environment variable for now.

## Acceptance Criteria
1. The UDF client must accept a new environment `SCRIPT_OPTIONS_PARSER_VERSION=2` variable to switch to the CTPG based Sript Options parser.
2. If no option is given, the legacy parser should be used

**Comment by ckunki** [comment]
Proposal: use environment variables for activation.
